//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GettAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public string Destination { get; set; }
        public string Origin { get; set; }
        public int RiderID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public bool IsActive { get; set; }
        public string RiderName { get; set; }
        public string DriverName { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Riders Riders { get; set; }
    }
}
